package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/BanqueReactionsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reaction.idl
* Wednesday, October 12, 2016 5:43:51 PM PDT
*/

public interface BanqueReactionsOperations 
{
  ca.etsmtl.log720.lab1.CollectionReaction reactions ();
  void ajouterReaction (String reaction, int gravite);
  ca.etsmtl.log720.lab1.CollectionReaction trouverReactionsParDossier (ca.etsmtl.log720.lab1.Dossier myDossier);
  ca.etsmtl.log720.lab1.Reaction trouverReactionParId (int idReaction);
} // interface BanqueReactionsOperations
