package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/BanqueInfractions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Infraction.idl
* samedi 1 octobre 2016 17 h 19 EDT
*/

public interface BanqueInfractions extends BanqueInfractionsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BanqueInfractions
