package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/BanqueDossiers.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dossier.idl
* samedi 1 octobre 2016 17 h 19 EDT
*/

public interface BanqueDossiers extends BanqueDossiersOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BanqueDossiers
