package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/BanqueInfractionsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Infraction.idl
* Wednesday, October 12, 2016 5:43:44 PM PDT
*/

public interface BanqueInfractionsOperations 
{
  ca.etsmtl.log720.lab1.CollectionInfraction infractions ();
  ca.etsmtl.log720.lab1.CollectionInfraction trouverInfractionsParDossier (ca.etsmtl.log720.lab1.Dossier mydossier);
  ca.etsmtl.log720.lab1.Infraction trouverInfractionParId (int idInfraction);
  void ajouterInfraction (String description, int niveau) throws ca.etsmtl.log720.lab1.NiveauHorsBornesException;
} // interface BanqueInfractionsOperations
