package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/BanqueReactionsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reaction.idl
* Wednesday, October 12, 2016 5:43:51 PM PDT
*/

public abstract class BanqueReactionsPOA extends org.omg.PortableServer.Servant
 implements ca.etsmtl.log720.lab1.BanqueReactionsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_reactions", new java.lang.Integer (0));
    _methods.put ("ajouterReaction", new java.lang.Integer (1));
    _methods.put ("trouverReactionsParDossier", new java.lang.Integer (2));
    _methods.put ("trouverReactionParId", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ca/etsmtl/log720/lab1/BanqueReactions/_get_reactions
       {
         ca.etsmtl.log720.lab1.CollectionReaction $result = null;
         $result = this.reactions ();
         out = $rh.createReply();
         ca.etsmtl.log720.lab1.CollectionReactionHelper.write (out, $result);
         break;
       }

       case 1:  // ca/etsmtl/log720/lab1/BanqueReactions/ajouterReaction
       {
         String reaction = in.read_string ();
         int gravite = in.read_long ();
         this.ajouterReaction (reaction, gravite);
         out = $rh.createReply();
         break;
       }

       case 2:  // ca/etsmtl/log720/lab1/BanqueReactions/trouverReactionsParDossier
       {
         ca.etsmtl.log720.lab1.Dossier myDossier = ca.etsmtl.log720.lab1.DossierHelper.read (in);
         ca.etsmtl.log720.lab1.CollectionReaction $result = null;
         $result = this.trouverReactionsParDossier (myDossier);
         out = $rh.createReply();
         ca.etsmtl.log720.lab1.CollectionReactionHelper.write (out, $result);
         break;
       }

       case 3:  // ca/etsmtl/log720/lab1/BanqueReactions/trouverReactionParId
       {
         int idReaction = in.read_long ();
         ca.etsmtl.log720.lab1.Reaction $result = null;
         $result = this.trouverReactionParId (idReaction);
         out = $rh.createReply();
         ca.etsmtl.log720.lab1.ReactionHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ca/etsmtl/log720/lab1/BanqueReactions:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BanqueReactions _this() 
  {
    return BanqueReactionsHelper.narrow(
    super._this_object());
  }

  public BanqueReactions _this(org.omg.CORBA.ORB orb) 
  {
    return BanqueReactionsHelper.narrow(
    super._this_object(orb));
  }


} // class BanqueReactionsPOA
