package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/BanqueReactions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reaction.idl
* Wednesday, October 12, 2016 5:43:51 PM PDT
*/

public interface BanqueReactions extends BanqueReactionsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BanqueReactions
