package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/BanqueInfractionsPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Infraction.idl
* samedi 1 octobre 2016 15 h 57 EDT
*/

public abstract class BanqueInfractionsPOA extends org.omg.PortableServer.Servant
 implements ca.etsmtl.log720.lab1.BanqueInfractionsOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_infractions", new java.lang.Integer (0));
    _methods.put ("trouverInfractionsParDossier", new java.lang.Integer (1));
    _methods.put ("trouverInfractionParId", new java.lang.Integer (2));
    _methods.put ("ajouterInfraction", new java.lang.Integer (3));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ca/etsmtl/log720/lab1/BanqueInfractions/_get_infractions
       {
         ca.etsmtl.log720.lab1.CollectionInfraction $result = null;
         $result = this.infractions ();
         out = $rh.createReply();
         ca.etsmtl.log720.lab1.CollectionInfractionHelper.write (out, $result);
         break;
       }

       case 1:  // ca/etsmtl/log720/lab1/BanqueInfractions/trouverInfractionsParDossier
       {
         ca.etsmtl.log720.lab1.Dossier mydossier = ca.etsmtl.log720.lab1.DossierHelper.read (in);
         ca.etsmtl.log720.lab1.CollectionInfraction $result = null;
         $result = this.trouverInfractionsParDossier (mydossier);
         out = $rh.createReply();
         ca.etsmtl.log720.lab1.CollectionInfractionHelper.write (out, $result);
         break;
       }

       case 2:  // ca/etsmtl/log720/lab1/BanqueInfractions/trouverInfractionParId
       {
         int idInfraction = in.read_long ();
         ca.etsmtl.log720.lab1.Infraction $result = null;
         $result = this.trouverInfractionParId (idInfraction);
         out = $rh.createReply();
         ca.etsmtl.log720.lab1.InfractionHelper.write (out, $result);
         break;
       }

       case 3:  // ca/etsmtl/log720/lab1/BanqueInfractions/ajouterInfraction
       {
         try {
           String description = in.read_string ();
           int niveau = in.read_long ();
           this.ajouterInfraction (description, niveau);
           out = $rh.createReply();
         } catch (ca.etsmtl.log720.lab1.NiveauHorsBornesException $ex) {
           out = $rh.createExceptionReply ();
           ca.etsmtl.log720.lab1.NiveauHorsBornesExceptionHelper.write (out, $ex);
         }
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ca/etsmtl/log720/lab1/BanqueInfractions:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public BanqueInfractions _this() 
  {
    return BanqueInfractionsHelper.narrow(
    super._this_object());
  }

  public BanqueInfractions _this(org.omg.CORBA.ORB orb) 
  {
    return BanqueInfractionsHelper.narrow(
    super._this_object(orb));
  }


} // class BanqueInfractionsPOA
