package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/BanqueInfractions.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Infraction.idl
* Wednesday, October 12, 2016 5:43:44 PM PDT
*/

public interface BanqueInfractions extends BanqueInfractionsOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface BanqueInfractions
