package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/CollectionReactionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reaction.idl
* Wednesday, October 12, 2016 5:43:51 PM PDT
*/

public interface CollectionReactionOperations 
{
  int size ();
  ca.etsmtl.log720.lab1.Reaction getReaction (int index);
} // interface CollectionReactionOperations
