package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/CollectionDossierOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dossier.idl
* Wednesday, October 12, 2016 5:43:37 PM PDT
*/

public interface CollectionDossierOperations 
{
  ca.etsmtl.log720.lab1.Dossier getDossier (int index);
  int size ();
} // interface CollectionDossierOperations
