package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/CollectionReactionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reaction.idl
* samedi 1 octobre 2016 17 h 18 EDT
*/

public interface CollectionReactionOperations 
{
  int size ();
  ca.etsmtl.log720.lab1.Reaction getReaction (int index);
} // interface CollectionReactionOperations
