package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/Dossier.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dossier.idl
* Wednesday, October 12, 2016 5:43:37 PM PDT
*/

public interface Dossier extends DossierOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Dossier
