package ca.etsmtl.log720.lab1;

/**
* ca/etsmtl/log720/lab1/DossierHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dossier.idl
* samedi 1 octobre 2016 17 h 19 EDT
*/

public final class DossierHolder implements org.omg.CORBA.portable.Streamable
{
  public ca.etsmtl.log720.lab1.Dossier value = null;

  public DossierHolder ()
  {
  }

  public DossierHolder (ca.etsmtl.log720.lab1.Dossier initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ca.etsmtl.log720.lab1.DossierHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ca.etsmtl.log720.lab1.DossierHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ca.etsmtl.log720.lab1.DossierHelper.type ();
  }

}
