package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/DossierPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dossier.idl
* Wednesday, October 12, 2016 5:43:37 PM PDT
*/

public abstract class DossierPOA extends org.omg.PortableServer.Servant
 implements ca.etsmtl.log720.lab1.DossierOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("_get_id", new java.lang.Integer (0));
    _methods.put ("_get_nom", new java.lang.Integer (1));
    _methods.put ("_get_noPermis", new java.lang.Integer (2));
    _methods.put ("_get_noPlaque", new java.lang.Integer (3));
    _methods.put ("_get_prenom", new java.lang.Integer (4));
    _methods.put ("_get_niveau", new java.lang.Integer (5));
    _methods.put ("getListeInfraction", new java.lang.Integer (6));
    _methods.put ("getListeReaction", new java.lang.Integer (7));
    _methods.put ("ajouterReactionAListe", new java.lang.Integer (8));
    _methods.put ("ajouterInfractionAListe", new java.lang.Integer (9));
    _methods.put ("toString", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ca/etsmtl/log720/lab1/Dossier/_get_id
       {
         int $result = (int)0;
         $result = this.id ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // ca/etsmtl/log720/lab1/Dossier/_get_nom
       {
         String $result = null;
         $result = this.nom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // ca/etsmtl/log720/lab1/Dossier/_get_noPermis
       {
         String $result = null;
         $result = this.noPermis ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 3:  // ca/etsmtl/log720/lab1/Dossier/_get_noPlaque
       {
         String $result = null;
         $result = this.noPlaque ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // ca/etsmtl/log720/lab1/Dossier/_get_prenom
       {
         String $result = null;
         $result = this.prenom ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // ca/etsmtl/log720/lab1/Dossier/_get_niveau
       {
         int $result = (int)0;
         $result = this.niveau ();
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 6:  // ca/etsmtl/log720/lab1/Dossier/getListeInfraction
       {
         int $result[] = null;
         $result = this.getListeInfraction ();
         out = $rh.createReply();
         ca.etsmtl.log720.lab1.ListeInfractionHelper.write (out, $result);
         break;
       }

       case 7:  // ca/etsmtl/log720/lab1/Dossier/getListeReaction
       {
         int $result[] = null;
         $result = this.getListeReaction ();
         out = $rh.createReply();
         ca.etsmtl.log720.lab1.ListeReactionHelper.write (out, $result);
         break;
       }

       case 8:  // ca/etsmtl/log720/lab1/Dossier/ajouterReactionAListe
       {
         int idReaction = in.read_long ();
         this.ajouterReactionAListe (idReaction);
         out = $rh.createReply();
         break;
       }

       case 9:  // ca/etsmtl/log720/lab1/Dossier/ajouterInfractionAListe
       {
         int idInfraction = in.read_long ();
         this.ajouterInfractionAListe (idInfraction);
         out = $rh.createReply();
         break;
       }

       case 10:  // ca/etsmtl/log720/lab1/Dossier/_toString
       {
         String $result = null;
         $result = this._toString ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ca/etsmtl/log720/lab1/Dossier:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Dossier _this() 
  {
    return DossierHelper.narrow(
    super._this_object());
  }

  public Dossier _this(org.omg.CORBA.ORB orb) 
  {
    return DossierHelper.narrow(
    super._this_object(orb));
  }


} // class DossierPOA
