package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/InfractionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Infraction.idl
* samedi 1 octobre 2016 17 h 19 EDT
*/

public interface InfractionOperations 
{
  int id ();
  String description ();
  int niveau ();
  String _toString ();
} // interface InfractionOperations
