package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/ListeInfractionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dossier.idl
* samedi 1 octobre 2016 17 h 19 EDT
*/

public final class ListeInfractionHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public ListeInfractionHolder ()
  {
  }

  public ListeInfractionHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ca.etsmtl.log720.lab1.ListeInfractionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ca.etsmtl.log720.lab1.ListeInfractionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ca.etsmtl.log720.lab1.ListeInfractionHelper.type ();
  }

}
