package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/NiveauHorsBornesException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Infraction.idl
* Wednesday, October 12, 2016 5:43:44 PM PDT
*/

public final class NiveauHorsBornesException extends org.omg.CORBA.UserException
{

  public NiveauHorsBornesException ()
  {
    super(NiveauHorsBornesExceptionHelper.id());
  } // ctor


  public NiveauHorsBornesException (String $reason)
  {
    super(NiveauHorsBornesExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NiveauHorsBornesException
