package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/NoPermisExisteDejaException.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Dossier.idl
* samedi 1 octobre 2016 17 h 19 EDT
*/

public final class NoPermisExisteDejaException extends org.omg.CORBA.UserException
{

  public NoPermisExisteDejaException ()
  {
    super(NoPermisExisteDejaExceptionHelper.id());
  } // ctor


  public NoPermisExisteDejaException (String $reason)
  {
    super(NoPermisExisteDejaExceptionHelper.id() + "  " + $reason);
  } // ctor

} // class NoPermisExisteDejaException
