package ca.etsmtl.log720.lab1;


/**
* ca/etsmtl/log720/lab1/ReactionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reaction.idl
* samedi 1 octobre 2016 17 h 18 EDT
*/

public interface ReactionOperations 
{
  int id ();
  String description ();
  int niveau ();
  String _toString ();
} // interface ReactionOperations
